"""gete terraform: the module calls it writes, and that they stay in step."""

import re
from pathlib import Path
from typing import Any

import pytest
from conftest import ProjectBuilder

import gete
from gete.declaration import load_project
from gete.terraform import check_generated, generate, write_generated

MODULE_DIR = Path(__file__).resolve().parents[1] / "terraform" / "agent_engine"

FULL_AGENT: dict[str, Any] = {
    "runtime": {
        "agent_engine": {
            "env": {"FREEE_COMPANY_ID": "123456"},
            "secret_env": {"SOME_TOKEN": "some-secret-name"},
            "min_instances": 1,
            "max_instances": 2,
            "python_version": "3.12",
        }
    }
}


def files(project: ProjectBuilder, out: str = "terraform") -> dict[str, str]:
    loaded = load_project(project.root / "gete.yaml")
    return generate(loaded, project.root / out)


def test_one_file_per_agent_named_with_underscores(project: ProjectBuilder) -> None:
    project.write_agent("mail-triage")
    project.write_agent("partner-review")
    assert set(files(project)) == {"mail_triage.tf", "partner_review.tf"}


def test_module_call_carries_project_location_and_identity(
    project: ProjectBuilder,
) -> None:
    project.write_agent("mail-triage")
    text = files(project)["mail_triage.tf"]
    assert text.startswith("# Generated by gete")
    assert 'module "mail_triage" {' in text
    assert f'ref=v{gete.__version__}"' in text
    assert 'project_id   = "example-project"' in text
    assert 'location     = "us-central1"' in text
    assert 'name         = "mail-triage"' in text
    assert 'display_name = "Mail triage"' in text
    assert 'agent_directory = "${path.module}/../agents/mail-triage"' in text


def test_runtime_settings_are_emitted_only_when_declared(
    project: ProjectBuilder,
) -> None:
    project.write_agent("plain")
    project.write_agent("full", FULL_AGENT)
    generated = files(project)
    plain, full = generated["plain.tf"], generated["full.tf"]
    for key in (
        "env",
        "secret_env",
        "min_instances",
        "max_instances",
        "python_version",
    ):
        assert key not in plain
    assert 'FREEE_COMPANY_ID = "123456"' in full
    assert 'SOME_TOKEN = "some-secret-name"' in full
    assert "min_instances  = 1" in full
    assert "max_instances  = 2" in full
    assert 'python_version = "3.12"' in full


def test_strings_are_escaped_for_hcl(project: ProjectBuilder) -> None:
    project.write_agent(
        "mail-triage", {"description": 'Says "hi" and ${not_interpolated} %{nor_this}'}
    )
    text = files(project)["mail_triage.tf"]
    assert r'description  = "Says \"hi\" and $${not_interpolated} %%{nor_this}"' in text


def test_module_source_can_be_overridden_in_gete_yaml(project: ProjectBuilder) -> None:
    project.write_project(
        {
            "version": 1,
            "project": "example-project",
            "location": "us-central1",
            "terraform": {"module_source": "../gete/terraform/agent_engine"},
        }
    )
    project.write_agent("mail-triage")
    assert (
        'source = "../gete/terraform/agent_engine"' in files(project)["mail_triage.tf"]
    )


def test_every_emitted_key_is_a_module_variable_and_required_ones_are_always_set(
    project: ProjectBuilder,
) -> None:
    """The generator and the module must agree; a typo would only fail at plan time."""
    project.write_agent("full", FULL_AGENT)
    body = files(project)["full.tf"]
    emitted = set(re.findall(r"^\s{2}(\w+)\s*=", body, re.MULTILINE))
    variables = {
        name: "default" in block
        for name, block in re.findall(
            r'variable "(\w+)" \{(.*?)\n\}',
            (MODULE_DIR / "variables.tf").read_text(),
            re.S,
        )
    }
    assert emitted - {"source"} <= set(variables)
    required = {name for name, has_default in variables.items() if not has_default}
    assert required <= emitted


def test_check_passes_right_after_writing(project: ProjectBuilder) -> None:
    project.write_agent("mail-triage")
    out = project.root / "terraform"
    write_generated(load_project(project.root / "gete.yaml"), out)
    assert check_generated(load_project(project.root / "gete.yaml"), out) == []


def test_check_fails_when_the_declaration_changed_and_files_were_not_regenerated(
    project: ProjectBuilder,
) -> None:
    project.write_agent("mail-triage")
    out = project.root / "terraform"
    write_generated(load_project(project.root / "gete.yaml"), out)
    project.write_agent("mail-triage", {"display_name": "Renamed"})
    project.write_agent("new-agent")
    differences = check_generated(load_project(project.root / "gete.yaml"), out)
    assert any("mail_triage.tf" in d for d in differences)
    assert any("new_agent.tf" in d for d in differences)


def test_check_flags_generated_files_whose_agent_is_gone(
    project: ProjectBuilder,
) -> None:
    project.write_agent("mail-triage")
    out = project.root / "terraform"
    write_generated(load_project(project.root / "gete.yaml"), out)
    (out / "old_agent.tf").write_text("# Generated by gete 0.0.0. Do not edit.\n")
    (out / "main.tf").write_text("# hand written, left alone\n")
    differences = check_generated(load_project(project.root / "gete.yaml"), out)
    assert any("old_agent.tf" in d for d in differences)
    assert not any("main.tf" in d for d in differences)


@pytest.mark.skipif(not MODULE_DIR.is_dir(), reason="module not checked out")
def test_generated_file_is_valid_hcl_for_terraform_fmt(
    project: ProjectBuilder, tmp_path: Path
) -> None:
    """terraform fmt -check is the cheapest syntax check that needs no providers."""
    import shutil
    import subprocess

    if shutil.which("terraform") is None:
        pytest.skip("terraform not installed")
    project.write_agent("full", FULL_AGENT)
    out = project.root / "terraform"
    write_generated(load_project(project.root / "gete.yaml"), out)
    result = subprocess.run(
        ["terraform", "fmt", "-check", "-diff", str(out / "full.tf")],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr
