"""Generating the Terraform that calls gete's module, one file per agent.

The declaration could be read by Terraform directly with yamldecode. Generating
instead makes what will be created readable as HCL, and leaves room next to
each call for the adjustments an installation needs (moved blocks, extra IAM).
The price is that generated files go stale, which --check exists to catch.
"""

import os
from collections.abc import Mapping
from importlib.metadata import version
from pathlib import Path, PurePosixPath
from typing import Any

from gete.declaration import Agent, Project
from gete.shared_credentials import SHARED_CREDENTIALS

# No version in the header: a development build's version changes with every
# commit, and --check would fail for files that are otherwise current.
HEADER = "# Generated by gete. Do not edit by hand; run `gete terraform` again.\n"
HEADER_PREFIX = "# Generated by gete"
DEFAULT_MODULE_SOURCE = (
    "git::https://github.com/pepabo/gete.git//terraform/agent_engine?ref=v{version}"
)


def hcl_string(value: str) -> str:
    """A quoted HCL string literal; interpolation sequences are escaped, not run."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("${", "$${")
        .replace("%{", "%%{")
    )
    return f'"{escaped}"'


def file_name(agent: Agent) -> str:
    return agent.name.replace("-", "_") + ".tf"


def generate(project: Project, out_dir: Path) -> dict[str, str]:
    """The files gete terraform would write into out_dir, keyed by file name."""
    gete_version = version("gete")
    terraform: Mapping[str, Any] = project.data.get("terraform", {})
    source = terraform.get("module_source") or DEFAULT_MODULE_SOURCE.format(
        version=gete_version
    )
    return {
        file_name(agent): _module_call(project, agent, out_dir, source)
        for agent in project.agents
    }


def write_generated(project: Project, out_dir: Path) -> list[Path]:
    """Write the files and return their paths. Other files in out_dir are left alone."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, text in generate(project, out_dir).items():
        path = out_dir / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def check_generated(project: Project, out_dir: Path) -> list[str]:
    """Differences between what would be written and what is on disk.

    Files that carry gete's header but no longer match an agent are reported
    too; a deleted agent must not keep its engine through a forgotten file.
    """
    expected = generate(project, out_dir)
    differences: list[str] = []
    for name, text in expected.items():
        path = out_dir / name
        if not path.is_file():
            differences.append(f"{path}: missing; run `gete terraform`")
        elif path.read_text(encoding="utf-8") != text:
            differences.append(f"{path}: out of date; run `gete terraform`")
    if out_dir.is_dir():
        for path in sorted(out_dir.glob("*.tf")):
            if path.name in expected:
                continue
            with path.open(encoding="utf-8") as handle:
                if handle.readline().startswith(HEADER_PREFIX):
                    differences.append(
                        f"{path}: generated for an agent that no longer exists"
                    )
    return differences


def _module_call(project: Project, agent: Agent, out_dir: Path, source: str) -> str:
    relative = PurePosixPath(
        os.path.relpath(agent.directory.resolve(), out_dir.resolve())
    ).as_posix()
    lines = [
        HEADER,
        f"module {hcl_string(agent.name.replace('-', '_'))} {{",
        f"  source = {hcl_string(source)}",
        "",
        f"  project_id   = {hcl_string(str(project.data['project']))}",
        f"  location     = {hcl_string(str(project.data['location']))}",
        f"  name         = {hcl_string(agent.name)}",
        f"  display_name = {hcl_string(str(agent.data['display_name']))}",
        f"  description  = {hcl_string(str(agent.data['description']))}",
        "",
        '  # gete packs the archive: the module\'s data "external" runs gete archive.',
        f'  agent_directory = "${{path.module}}/{relative}"',
    ]
    maps, scalars = _runtime_settings(project, agent)
    if maps or scalars:
        lines.append("")
    # terraform fmt aligns "=" only across consecutive single-line attributes,
    # so multi-line maps are written unpadded and the scalars after them as
    # one aligned group.
    lines.extend(f"  {key} = {value}" for key, value in maps.items())
    if scalars:
        width = max(len(key) for key in scalars)
        lines.extend(
            f"  {key.ljust(width)} = {value}" for key, value in scalars.items()
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def _shared_secret_env(project: Project, agent: Agent) -> dict[str, str]:
    """The token secrets of the agent's shared credentials, by their env names.

    Named once in gete.yaml: the agent declares that it uses the credential
    and gets the wiring, without writing - or being able to change - which
    secret the token comes from. No project entry, no invented name; validate
    reports the gap.
    """
    declared: Mapping[str, Any] = project.data.get("shared_credentials", {})
    wired: dict[str, str] = {}
    for name in agent.shared_credentials:
        secret = declared.get(name, {}).get("token_secret")
        if secret:
            wired[SHARED_CREDENTIALS[name].token_env] = str(secret)
    return wired


def _runtime_settings(
    project: Project, agent: Agent
) -> tuple[dict[str, str], dict[str, str]]:
    """(multi-line map attributes, single-line attributes), only those declared."""
    runtime: Mapping[str, Any] = agent.data.get("runtime", {}).get("agent_engine", {})
    maps: dict[str, str] = {}
    scalars: dict[str, str] = {}
    if runtime.get("env"):
        maps["env"] = _hcl_map(runtime["env"])
    secret_env = {**runtime.get("secret_env", {}), **_shared_secret_env(project, agent)}
    if secret_env:
        maps["secret_env"] = _hcl_map(secret_env)
    for key in ("min_instances", "max_instances"):
        if key in runtime:
            scalars[key] = str(runtime[key])
    if "python_version" in runtime:
        scalars["python_version"] = hcl_string(str(runtime["python_version"]))
    return maps, scalars


def _hcl_map(values: Mapping[str, str]) -> str:
    if not values:
        return "{}"
    width = max(len(key) for key in values)
    body = "\n".join(
        f"    {key.ljust(width)} = {hcl_string(value)}" for key, value in values.items()
    )
    return "{\n" + body + "\n  }"
