# Generated by gete. Do not edit by hand; run `gete terraform` again.

module "minimal" {
  source = "../../../terraform/agent_engine"

  project_id   = "example-project"
  location     = "us-central1"
  name         = "minimal"
  display_name = "Minimal"
  description  = "Answers questions about the text the user pastes. Has no tools."

  # gete packs the archive: the module's data "external" runs gete archive.
  agent_directory = "${path.module}/../agents/minimal"
}
